# Use OpenJDK 21 as the base image
FROM eclipse-temurin:21-jdk-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file from the local system to the container (adjust the file path as needed)
COPY build/libs/ims-0.0.1-SNAPSHOT.jar /app/ims.jar

# Expose the port your application will use (adjust the port if needed)
EXPOSE 8080

# Command to run the JAR file
ENTRYPOINT ["java", "-jar", "/app/ims.jar"]
