spring:
  application:
    name: ims
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}  # Reads from the environment variable
    password: ${SPRING_MAIL_PASSWORD}  # Reads from the environment variable
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}  # Reads from the environment variable
      database: ${SPRING_DATA_MONGODB_DATABASE}  # Reads from the environment variable
server:
  port: 8080
logging:
  level:
    root: INFO
    com:
      backend: DEBUG
    org:
      springframework:
        data:
          mongodb: DEBUG
