spring:
  application:
    name: ims
  mail:
    host: smtp.gmail.com
    port: 587
    username: test@gmail.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    mongodb:
      uri: mongodb+srv://ims:Kzavop5MIa05Bfu0@ims.fawiw.mongodb.net
      database: ims
server:
  port: 8080
logging:
  level:
    root: INFO
    com:
      backend: DEBUG
    org:
      springframework:
        data:
          mongodb: DEBUG
