spring:
  application:
    name: ims
  mail:
    host: ${spring.mail.host}
    port: ${spring.mail.port}
    username: ${spring.mail.username}
    password: ${spring.mail.password}
    properties:
      mail:
        smtp:
          auth: ${spring.mail.properties.mail.smtp.auth}
          starttls:
            enable: ${spring.mail.properties.mail.smtp.starttls.enable}
  data:
    mongodb:
      uri: ${spring.data.mongodb.uri}
      database: ${spring.data.mongodb.database}
server:
  port: 8080
logging:
  level:
    root: INFO
    com:
      backend: DEBUG
    org:
      springframework:
        data:
          mongodb: DEBUG
