spring:
  application:
    name: ims
  mail:
    host: smtp.gmail.com
    port: 587
    username: test@gmail.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    mongodb:
      uri: mongodb+srv://ims:Kzavop5MIa05Bfu0@ims.fawiw.mongodb.net/?maxPoolSize=1&socketTimeoutMS=5000&connectTimeoutMS=5000&retryWrites=true&compressors=zlib
      database: ims
server:
  port: 443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: imsbackend
    key-store-type: PKCS12
    key-alias: ims
