name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Change Wrapper Permission
        run: chmod +x ./gradlew
      - name: Build with Gradle Wrapper
        run: ./gradlew build
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: build/

  jacoco-coverage:
    if: ${{ github.event.pull_request }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Change Wrapper Permission
        run: chmod +x ./gradlew
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: build/
      - name: Run Tests with Coverage
        run: ./gradlew test jacocoTestReport
      - name: Fetch Base Branch (master)
        run: |
          git remote add upstream https://github.com/thesis-ims/ims-backend.git
          git fetch upstream master
        if: github.event.pull_request.head.repo.fork == true
      - name: Set Base Branch
        run: |
          if [[ "${{ github.event.pull_request.head.repo.fork }}" == "true" ]]; then
            echo "BASE_BRANCH=upstream/master" >> $GITHUB_ENV
          else
            echo "BASE_BRANCH=origin/master" >> $GITHUB_ENV
          fi
      - name: Install diff-cover
        run: pip install diff-cover
      - name: Generate Coverage Report
        run: |
          diff-cover build/jacocoReports/test/jacocoTestReport.xml --compare-branch ${{ env.BASE_BRANCH }} --markdown-report coverage-report.md
      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/jacocoReports/test/html/
      - name: Post Coverage Report as PR Comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('coverage-report.md', 'utf8');
            await github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### JaCoCo Coverage Report\n\n${report}`
            });

  dependency-submission:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Generate and Submit Dependency Graph
        uses: gradle/actions/dependency-submission@v4
        with:
          token: ${{ secrets.PAT }}
