name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Change Wrapper Permission
        run: chmod +x ./gradlew
      - name: Build with Gradle Wrapper
        run: ./gradlew build

  dependency-submission:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' # Run only on push to master
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Generate and Submit Dependency Graph
        uses: gradle/actions/dependency-submission@v4
        with:
          token: ${{ secrets.PAT }}