name: Gradle Package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3 # using version tag for stability

      - name: Build with Gradle
        run: ./gradlew build

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Create Release
        id: create_release
        run: |
          REPO=${{ github.repository }}
          TAG=${{ github.ref_name }}
          BODY="Release of version $TAG"
          gh release create $TAG build/libs/ims-data-0.0.1-SNAPSHOT.jar --title "Release $TAG" --notes "$BODY"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}